### ISSUE TITLE
更改soc之乱

### ISSUE THREAD

**Issue by singer01** [HCWiki/history#10]
这个名字非常不合适，首先事实是里面一群牛鬼蛇神围攻我，怎么能叫乱？其次soc这个名称太奇怪了，改成Socialist或者GPCR都可以。
建议改名为”反动派围攻GPCR“，并且内容也需要修改，添加列举走资派罪行的内容！

**Comment by cmd1152** [comment]
你自己不就是反动派吗

**Comment by singer01** [comment]
> 你自己不就是反动派吗

我怎么反动了？支持共产主义是反动？

**Comment by cmd1152** [comment]
> > 你自己不就是反动派吗
> 
> 我怎么反动了？支持共产主义是反动？

那你有什么理由说我们是反动派？

**Comment by singer01** [comment]
> > > 你自己不就是反动派吗
> > 
> > 
> > 我怎么反动了？支持共产主义是反动？
> 
> 那你有什么理由说我们是反动派？

那个2不是反动派？他反对共产主义，支持资本主义复辟。

**Comment by singer01** [comment]
急了就封禁？
